FROM docker.xuanyuan.run/library/node:24-bookworm-slim AS web-build

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY
ARG NO_PROXY
ENV HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY} NO_PROXY=${NO_PROXY}

WORKDIR /src/web
COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

FROM docker.xuanyuan.run/library/nginx:1.29-alpine AS web-runtime

COPY deploy/nginx/web.conf.template /etc/nginx/templates/default.conf.template
COPY --from=web-build /src/web/dist /usr/share/nginx/html

EXPOSE 80
